# Source this file INSIDE Innovus with the intended design/timing state loaded.
# Plain tclsh cannot query an Innovus timing database.
namespace eval ::iv2 {variable base [file dirname [file normalize [info script]]]}
foreach file {innovus_attributes.tcl innovus_io.tcl innovus_adapter.tcl} {
    source [file join $::iv2::base $file]
}

proc ::iv2::run {targets_file output_file} {
    foreach cmd {report_timing get_property get_pins get_ports sizeof_collection foreach_in_collection} {
        if {![llength [info commands ::$cmd]]} {error "Missing $cmd: run inside Innovus"}
    }
    # targets.tcl is generated by prepare; source only your own generated job.
    source $targets_file
    variable job_config
    variable targets
    set cfg $job_config
    if {[file exists $output_file]} {error "Output already exists: $output_file. Choose a new file."}
    file mkdir [file dirname $output_file]
    set temporary ${output_file}.partial
    set f [open $temporary {WRONLY CREAT EXCL}]
    fconfigure $f -encoding utf-8 -translation lf
    set count 0
    set errors 0
    set version unknown
    if {[llength [info commands ::getVersion]]} {catch {set version [getVersion]}}
    set code [catch {
        puts $f [jo [dict create record_type [js header] schema_version [js 2.0] \
            job_id [js [dict get $cfg job_id]] tool [js Innovus] tool_version [js $version] \
            config [jstrings $cfg] adapter_path_fields [jstrings $::iv2::path_fields] \
            adapter_point_fields [jstrings $::iv2::point_fields]]]
        foreach target $targets {
            set encoded {}
            set command {}
            set status ok
            set message {}
            set truncated false
            set code_one [catch {
                set result [query $target $cfg]
                set command [dict get $result command]
                set collection [dict get $result paths]
                if {[sizeof_collection $collection] > [dict get $cfg candidate_limit]} {set truncated true}
                set index 0
                foreach_in_collection path $collection {
                    lappend encoded [candidate_json $path [incr index]]
                }
                if {$index == 0} {set status not_found}
            } message]
            if {$code_one} {set status query_error; set encoded {}; incr errors} else {set message {}}
            puts $f [jo [dict create record_type [js target] \
                target_id [js [dict get $target target_id]] golden_index [dict get $target golden_index] \
                query_from [js [dict get $target query_from]] query_to [js [dict get $target query_to]] \
                status [js $status] message [js $message] command [js $command] \
                truncated $truncated candidates [ja $encoded]]]
            incr count
            if {$count % 100 == 0} {puts "iv2: $count / [llength $targets] targets"; flush $f}
        }
        puts $f [jo [dict create record_type [js footer] complete true target_count $count query_errors $errors]]
    } message options]
    close $f
    if {$code} {return -options $options $message}
    file rename $temporary $output_file
    puts "iv2: wrote $count targets ($errors query errors): $output_file"
    return $output_file
}
